2020-03-29T10:13:08-0300 [-] Creating router ...
2020-03-29T10:13:08-0300 [-] Initializing Router - Number of events: 1
2020-03-29T10:13:08-0300 [-] RouterFactory starting on 8081
2020-03-29T10:13:08-0300 [-] Creating AccessPoint station ...
2020-03-29T10:13:08-0300 [-] Initializing Access Point - Number of events: 2
2020-03-29T10:13:09-0300 [-] Creating AccessPoint station ...
2020-03-29T10:13:09-0300 [-] Initializing Access Point - Number of events: 3
2020-03-29T10:13:09-0300 [-] Creating fog node ...
2020-03-29T10:13:09-0300 [-] Initializing Client - Number of events: 4
2020-03-29T10:13:10-0300 [-] Creating fog node ...
2020-03-29T10:13:10-0300 [-] Initializing Server - Number of events: 5
2020-03-29T10:13:10-0300 [-] BrokerFactory starting on 5100
2020-03-29T10:13:10-0300 [-] Creating iot node ...
2020-03-29T10:13:10-0300 [-] Initializing Client - Number of events: 6
2020-03-29T10:13:11-0300 [-] Creating iot node ...
2020-03-29T10:13:11-0300 [-] Initializing Client - Number of events: 7
2020-03-29T10:13:11-0300 [stdout#info] This divice have no simulation core instance
2020-03-29T10:13:11-0300 [stdout#info] This divice have no simulation core instance
2020-03-29T10:13:11-0300 [stdout#info] This divice have no simulation core instance
2020-03-29T10:13:11-0300 [stdout#info] This divice have no simulation core instance
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50892 - Connected to mqtt broker - Number of events: 8
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50892 - sending MQTT SUBSCRIBE REQUEST - Number of events: 9
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50894 - Connected to mqtt broker - Number of events: 10
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50896 - Connected to mqtt broker - Number of events: 12
2020-03-29T10:13:11-0300 [Uninitialized] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-03-29T10:13:11-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50892, "type": "http", "payload": {"action": "subscribe", "topic": "sensor_metering", "content": "None"}}\n'
2020-03-29T10:13:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80d4d68>
2020-03-29T10:13:11-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "8.74 Kwh"}}\n'
2020-03-29T10:13:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80d4f60>
2020-03-29T10:13:12-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "9.62 Kwh"}}\n'
2020-03-29T10:13:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394240>
2020-03-29T10:13:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80d4d68>
2020-03-29T10:13:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80d4f60>
2020-03-29T10:13:12-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:12-0300 [ClientProtocol,client] connection lost - Number of events: 14
2020-03-29T10:13:12-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394240>
2020-03-29T10:13:12-0300 [BrokerProtocol,0,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:12-0300 [BrokerProtocol,1,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:12-0300 [BrokerProtocol,2,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:16-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-03-29T10:13:17-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-03-29T10:13:17-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "22.12 Kwh"}}\n'
2020-03-29T10:13:17-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80aba90>
2020-03-29T10:13:17-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "9.71 Kwh"}}\n'
2020-03-29T10:13:17-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23948d0>
2020-03-29T10:13:22-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 17
2020-03-29T10:13:22-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-03-29T10:13:22-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "22.33 Kwh"}}\n'
2020-03-29T10:13:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394ba8>
2020-03-29T10:13:22-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "13.53 Kwh"}}\n'
2020-03-29T10:13:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394da0>
2020-03-29T10:13:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d80aba90>
2020-03-29T10:13:22-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:22-0300 [ClientProtocol,client] connection lost - Number of events: 19
2020-03-29T10:13:22-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23948d0>
2020-03-29T10:13:22-0300 [BrokerProtocol,3,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:22-0300 [BrokerProtocol,3,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:22-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:22-0300 [BrokerProtocol,4,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:27-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 20
2020-03-29T10:13:27-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-03-29T10:13:27-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "11.87 Kwh"}}\n'
2020-03-29T10:13:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b50b8>
2020-03-29T10:13:27-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "8.29 Kwh"}}\n'
2020-03-29T10:13:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5780>
2020-03-29T10:13:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394ba8>
2020-03-29T10:13:27-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:27-0300 [ClientProtocol,client] connection lost - Number of events: 22
2020-03-29T10:13:27-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2394da0>
2020-03-29T10:13:27-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-03-29T10:13:27-0300 [BrokerProtocol,5,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:27-0300 [BrokerProtocol,5,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:27-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:27-0300 [BrokerProtocol,6,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:32-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 23
2020-03-29T10:13:32-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-03-29T10:13:32-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "6.27 Kwh"}}\n'
2020-03-29T10:13:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b59e8>
2020-03-29T10:13:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b50b8>
2020-03-29T10:13:32-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "18.85 Kwh"}}\n'
2020-03-29T10:13:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5b70>
2020-03-29T10:13:32-0300 [BrokerProtocol,7,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:32-0300 [BrokerProtocol,7,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:32-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:32-0300 [ClientProtocol,client] connection lost - Number of events: 25
2020-03-29T10:13:32-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5780>
2020-03-29T10:13:32-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-03-29T10:13:32-0300 [BrokerProtocol,8,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:32-0300 [BrokerProtocol,8,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:37-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 26
2020-03-29T10:13:37-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-03-29T10:13:37-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "5.24 Kwh"}}\n'
2020-03-29T10:13:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5e10>
2020-03-29T10:13:37-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "14.2 Kwh"}}\n'
2020-03-29T10:13:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d14f4b38>
2020-03-29T10:13:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b59e8>
2020-03-29T10:13:37-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:37-0300 [ClientProtocol,client] connection lost - Number of events: 28
2020-03-29T10:13:37-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5b70>
2020-03-29T10:13:37-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-03-29T10:13:37-0300 [BrokerProtocol,9,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:37-0300 [BrokerProtocol,9,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:37-0300 [BrokerProtocol,10,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:37-0300 [BrokerProtocol,10,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:42-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 29
2020-03-29T10:13:42-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-03-29T10:13:42-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "15.74 Kwh"}}\n'
2020-03-29T10:13:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23244a8>
2020-03-29T10:13:42-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "21.04 Kwh"}}\n'
2020-03-29T10:13:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23242e8>
2020-03-29T10:13:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23b5e10>
2020-03-29T10:13:42-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:42-0300 [ClientProtocol,client] connection lost - Number of events: 31
2020-03-29T10:13:42-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d14f4b38>
2020-03-29T10:13:42-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-03-29T10:13:42-0300 [BrokerProtocol,11,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:42-0300 [BrokerProtocol,11,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:42-0300 [BrokerProtocol,12,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:42-0300 [BrokerProtocol,12,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:47-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 32
2020-03-29T10:13:47-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-03-29T10:13:47-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "8.96 Kwh"}}\n'
2020-03-29T10:13:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324668>
2020-03-29T10:13:47-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "4.72 Kwh"}}\n'
2020-03-29T10:13:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324898>
2020-03-29T10:13:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23244a8>
2020-03-29T10:13:47-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:47-0300 [ClientProtocol,client] connection lost - Number of events: 34
2020-03-29T10:13:47-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d23242e8>
2020-03-29T10:13:47-0300 [BrokerProtocol,13,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:47-0300 [BrokerProtocol,13,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:47-0300 [BrokerProtocol,14,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:47-0300 [BrokerProtocol,14,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:52-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 35
2020-03-29T10:13:52-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-03-29T10:13:52-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "6.22 Kwh"}}\n'
2020-03-29T10:13:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324dd8>
2020-03-29T10:13:52-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "12.02 Kwh"}}\n'
2020-03-29T10:13:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324fd0>
2020-03-29T10:13:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324668>
2020-03-29T10:13:52-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:52-0300 [ClientProtocol,client] connection lost - Number of events: 37
2020-03-29T10:13:52-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324898>
2020-03-29T10:13:52-0300 [BrokerProtocol,15,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:52-0300 [BrokerProtocol,15,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:52-0300 [BrokerProtocol,16,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:52-0300 [BrokerProtocol,16,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:57-0300 [-] 127.0.0.1:50894 - sending MQTT PUBLISH REQUEST - Number of events: 38
2020-03-29T10:13:57-0300 [-] 127.0.0.1:50896 - sending MQTT PUBLISH REQUEST - Number of events: 39
2020-03-29T10:13:57-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50894, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "14.86 Kwh"}}\n'
2020-03-29T10:13:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0cb5518>
2020-03-29T10:13:57-0300 [stdout#info] OPACOTE É b'{"destiny_addr": "127.0.0.1", "destiny_port": 5100, "source_addr": "127.0.0.1", "source_port": 50896, "type": "http", "payload": {"action": "publish", "topic": "sensor_metering", "content": "22.27 Kwh"}}\n'
2020-03-29T10:13:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0cb5710>
2020-03-29T10:13:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324dd8>
2020-03-29T10:13:57-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-03-29T10:13:57-0300 [ClientProtocol,client] connection lost - Number of events: 40
2020-03-29T10:13:57-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2324fd0>
2020-03-29T10:13:57-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-03-29T10:13:57-0300 [BrokerProtocol,17,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:57-0300 [BrokerProtocol,17,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:13:57-0300 [BrokerProtocol,18,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 197, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-03-29T10:13:57-0300 [BrokerProtocol,18,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:14:01-0300 [-] Received SIGINT, shutting down.
2020-03-29T10:14:01-0300 [BrokerProtocol,19,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:14:01-0300 [ClientProtocol,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-03-29T10:14:01-0300 [ClientProtocol,client] connection lost - Number of events: 41
2020-03-29T10:14:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0cb5710>
2020-03-29T10:14:01-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-03-29T10:14:01-0300 [SubscriberApp,client] connection lost - Number of events: 42
2020-03-29T10:14:01-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-03-29T10:14:01-0300 [PublisherApp,client] connection lost - Number of events: 43
2020-03-29T10:14:01-0300 [BrokerProtocol,20,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-03-29T10:14:01-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-03-29T10:14:01-0300 [RouterAppProtocol,3,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-03-29T10:14:01-0300 [RouterAppProtocol,3,127.0.0.1] connection lost - Number of events: 44
2020-03-29T10:14:01-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-03-29T10:14:01-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-03-29T10:14:01-0300 [PublisherApp,client] connection lost - Number of events: 45
2020-03-29T10:14:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0cb5518>
2020-03-29T10:14:01-0300 [-] Main loop terminated.
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 153, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 95, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 209, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 214, in create_connection
	    x2 = self.device2.visual_component.x
	builtins.AttributeError: 'NoneType' object has no attribute 'visual_component'
	
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 153, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 95, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 209, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 214, in create_connection
	    x2 = self.device2.visual_component.x
	builtins.AttributeError: 'NoneType' object has no attribute 'visual_component'
	
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 153, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 95, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 209, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 214, in create_connection
	    x2 = self.device2.visual_component.x
	builtins.AttributeError: 'NoneType' object has no attribute 'visual_component'
	
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-03-29T10:14:01-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 153, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 95, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 209, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 214, in create_connection
	    x2 = self.device2.visual_component.x
	builtins.AttributeError: 'NoneType' object has no attribute 'visual_component'
	
