2020-02-25T12:40:13-0300 [-] Creating router ...
2020-02-25T12:40:13-0300 [-] Initializing Router - Number of events: 1
2020-02-25T12:40:13-0300 [-] ServerFactory starting on 8081
2020-02-25T12:40:13-0300 [stdout#info] {<applications.routerapp.RouterApp object at 0x7fc1d0998278>}
2020-02-25T12:40:13-0300 [stderr#error] Exception in Tkinter callback
2020-02-25T12:40:13-0300 [stderr#error] Traceback (most recent call last):
2020-02-25T12:40:13-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-02-25T12:40:13-0300 [stderr#error]     return self.func(*args)
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 101, in <lambda>
2020-02-25T12:40:13-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 55, in open_project
2020-02-25T12:40:13-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 134, in load_nodes
2020-02-25T12:40:13-0300 [stderr#error]     rt.run()
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 115, in run
2020-02-25T12:40:13-0300 [stderr#error]     self.application.start(self.addr, self.port)
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 46, in start
2020-02-25T12:40:13-0300 [stderr#error]     listenStarting.addCallback(self.save_protocol_in_simulation_core(self))
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 322, in addCallback
2020-02-25T12:40:13-0300 [stderr#error]     callbackKeywords=kw)
2020-02-25T12:40:13-0300 [stderr#error]   File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 304, in addCallbacks
2020-02-25T12:40:13-0300 [stderr#error]     assert callable(callback)
2020-02-25T12:40:13-0300 [stderr#error] AssertionError
2020-02-25T12:40:54-0300 [-] Received SIGINT, shutting down.
2020-02-25T12:40:54-0300 [twisted.internet.protocol.ServerFactory] (TCP Port 8081 Closed)
2020-02-25T12:40:54-0300 [-] Main loop terminated.
