2020-02-26T10:05:31-0300 [-] Creating router ...
2020-02-26T10:05:31-0300 [-] Initializing Router - Number of events: 1
2020-02-26T10:05:31-0300 [-] RouterFactory starting on 8081
2020-02-26T10:05:31-0300 [-] Creating fog node ...
2020-02-26T10:05:31-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-26T10:05:31-0300 [-] Initializing Client - Number of events: 2
2020-02-26T10:05:31-0300 [-] Creating fog node ...
2020-02-26T10:05:31-0300 [-] Initializing Server - Number of events: 3
2020-02-26T10:05:31-0300 [-] BrokerFactory starting on 5100
2020-02-26T10:05:31-0300 [-] Creating iot node ...
2020-02-26T10:05:31-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:05:31-0300 [-] Initializing Client - Number of events: 4
2020-02-26T10:05:31-0300 [-] Creating iot node ...
2020-02-26T10:05:31-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:05:31-0300 [-] Initializing Client - Number of events: 5
2020-02-26T10:05:31-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:05:31-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:05:31-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:05:31-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51332 - Connected to mqtt broker - Number of events: 6
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51332 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51334 - Connected to mqtt broker - Number of events: 8
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51336 - Connected to mqtt broker - Number of events: 10
2020-02-26T10:05:31-0300 [Uninitialized] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cb38>
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cd30>
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cf28>
2020-02-26T10:05:31-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cb38>
2020-02-26T10:05:31-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cd30>
2020-02-26T10:05:31-0300 [BrokerProtocol,0,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:31-0300 [BrokerProtocol,1,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:31-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7efca9b7ccf8>
	
2020-02-26T10:05:31-0300 [ClientProtocol,client] connection lost: <applications.routerapp.ClientProtocol object at 0x7efca9b7ccf8>
2020-02-26T10:05:31-0300 [ClientProtocol,client] connection lost - Number of events: 12
2020-02-26T10:05:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7cf28>
2020-02-26T10:05:31-0300 [BrokerProtocol,2,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:36-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-02-26T10:05:36-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-26T10:05:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd128>
2020-02-26T10:05:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd2e8>
2020-02-26T10:05:36-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:05:36-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd128>
2020-02-26T10:05:36-0300 [BrokerProtocol,3,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:41-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-26T10:05:41-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-26T10:05:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd668>
2020-02-26T10:05:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd828>
2020-02-26T10:05:41-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:05:41-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:05:41-0300 [BrokerProtocol,4,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:41-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd668>
2020-02-26T10:05:41-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:05:41-0300 [ClientProtocol,client] connection lost - Number of events: 17
2020-02-26T10:05:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd2e8>
2020-02-26T10:05:41-0300 [BrokerProtocol,5,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:46-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-02-26T10:05:46-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-26T10:05:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdda0>
2020-02-26T10:05:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdf98>
2020-02-26T10:05:46-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:05:46-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:05:46-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:05:46-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:05:46-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:05:46-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:05:46-0300 [BrokerProtocol,6,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:46-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:05:46-0300 [ClientProtocol,client] connection lost - Number of events: 20
2020-02-26T10:05:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd828>
2020-02-26T10:05:46-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdda0>
2020-02-26T10:05:46-0300 [BrokerProtocol,7,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:51-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 21
2020-02-26T10:05:51-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 22
2020-02-26T10:05:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fda20>
2020-02-26T10:05:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd9e8>
2020-02-26T10:05:51-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:05:51-0300 [BrokerProtocol,8,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:05:51-0300 [BrokerProtocol,8,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:51-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fda20>
2020-02-26T10:05:51-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:05:51-0300 [ClientProtocol,client] connection lost - Number of events: 23
2020-02-26T10:05:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdf98>
2020-02-26T10:05:51-0300 [BrokerProtocol,9,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:56-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 24
2020-02-26T10:05:56-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 25
2020-02-26T10:05:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f0f0>
2020-02-26T10:05:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f4e0>
2020-02-26T10:05:56-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:05:56-0300 [BrokerProtocol,10,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:05:56-0300 [BrokerProtocol,10,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:05:56-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:05:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f0f0>
2020-02-26T10:05:56-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:05:56-0300 [ClientProtocol,client] connection lost - Number of events: 26
2020-02-26T10:05:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd9e8>
2020-02-26T10:05:56-0300 [BrokerProtocol,11,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:01-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 27
2020-02-26T10:06:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f828>
2020-02-26T10:06:01-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 28
2020-02-26T10:06:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20fa58>
2020-02-26T10:06:01-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f828>
2020-02-26T10:06:01-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:01-0300 [BrokerProtocol,12,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:01-0300 [BrokerProtocol,12,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:01-0300 [BrokerProtocol,13,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:01-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:01-0300 [ClientProtocol,client] connection lost - Number of events: 29
2020-02-26T10:06:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f4e0>
2020-02-26T10:06:06-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 30
2020-02-26T10:06:06-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 31
2020-02-26T10:06:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20fdd8>
2020-02-26T10:06:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20ff98>
2020-02-26T10:06:06-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:06-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:06-0300 [BrokerProtocol,14,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:06-0300 [BrokerProtocol,14,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:06-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20fdd8>
2020-02-26T10:06:06-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:06-0300 [ClientProtocol,client] connection lost - Number of events: 32
2020-02-26T10:06:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20fa58>
2020-02-26T10:06:06-0300 [BrokerProtocol,15,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:11-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 33
2020-02-26T10:06:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f6a0>
2020-02-26T10:06:11-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 34
2020-02-26T10:06:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f0b8>
2020-02-26T10:06:11-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f6a0>
2020-02-26T10:06:11-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:11-0300 [BrokerProtocol,16,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:11-0300 [BrokerProtocol,16,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:11-0300 [BrokerProtocol,17,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:11-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:11-0300 [ClientProtocol,client] connection lost - Number of events: 35
2020-02-26T10:06:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20ff98>
2020-02-26T10:06:16-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 36
2020-02-26T10:06:16-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdef0>
2020-02-26T10:06:16-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 37
2020-02-26T10:06:16-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd128>
2020-02-26T10:06:16-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:16-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdef0>
2020-02-26T10:06:16-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:16-0300 [BrokerProtocol,18,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:16-0300 [BrokerProtocol,18,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:16-0300 [BrokerProtocol,19,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:16-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:16-0300 [ClientProtocol,client] connection lost - Number of events: 38
2020-02-26T10:06:16-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f0b8>
2020-02-26T10:06:21-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 39
2020-02-26T10:06:21-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 40
2020-02-26T10:06:21-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdc50>
2020-02-26T10:06:21-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdda0>
2020-02-26T10:06:21-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:21-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:21-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:21-0300 [BrokerProtocol,20,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:21-0300 [BrokerProtocol,20,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:21-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:21-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdc50>
2020-02-26T10:06:21-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:21-0300 [ClientProtocol,client] connection lost - Number of events: 41
2020-02-26T10:06:21-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd128>
2020-02-26T10:06:21-0300 [BrokerProtocol,21,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:26-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 42
2020-02-26T10:06:26-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 43
2020-02-26T10:06:26-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f5c0>
2020-02-26T10:06:26-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f390>
2020-02-26T10:06:26-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:26-0300 [BrokerProtocol,22,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:26-0300 [BrokerProtocol,22,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:26-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:26-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f5c0>
2020-02-26T10:06:26-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:26-0300 [ClientProtocol,client] connection lost - Number of events: 44
2020-02-26T10:06:26-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdda0>
2020-02-26T10:06:26-0300 [BrokerProtocol,23,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:31-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 45
2020-02-26T10:06:31-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 46
2020-02-26T10:06:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd208>
2020-02-26T10:06:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fda58>
2020-02-26T10:06:31-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:31-0300 [BrokerProtocol,24,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:31-0300 [BrokerProtocol,24,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:31-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd208>
2020-02-26T10:06:31-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:31-0300 [ClientProtocol,client] connection lost - Number of events: 47
2020-02-26T10:06:31-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f390>
2020-02-26T10:06:31-0300 [BrokerProtocol,25,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:36-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 48
2020-02-26T10:06:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcb28872e8>
2020-02-26T10:06:36-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 49
2020-02-26T10:06:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b252b0>
2020-02-26T10:06:36-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcb28872e8>
2020-02-26T10:06:36-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:36-0300 [BrokerProtocol,26,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:36-0300 [BrokerProtocol,26,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:36-0300 [BrokerProtocol,27,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:36-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:36-0300 [ClientProtocol,client] connection lost - Number of events: 50
2020-02-26T10:06:36-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fda58>
2020-02-26T10:06:41-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 51
2020-02-26T10:06:41-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 52
2020-02-26T10:06:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25630>
2020-02-26T10:06:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b257f0>
2020-02-26T10:06:41-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:41-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:41-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:41-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:41-0300 [BrokerProtocol,28,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:41-0300 [BrokerProtocol,28,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:41-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25630>
2020-02-26T10:06:41-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:41-0300 [ClientProtocol,client] connection lost - Number of events: 53
2020-02-26T10:06:41-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b252b0>
2020-02-26T10:06:41-0300 [BrokerProtocol,29,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:46-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 54
2020-02-26T10:06:46-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 55
2020-02-26T10:06:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f080>
2020-02-26T10:06:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdef0>
2020-02-26T10:06:46-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:46-0300 [BrokerProtocol,30,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:46-0300 [BrokerProtocol,30,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:46-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20f080>
2020-02-26T10:06:46-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:46-0300 [ClientProtocol,client] connection lost - Number of events: 56
2020-02-26T10:06:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b257f0>
2020-02-26T10:06:46-0300 [BrokerProtocol,31,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:51-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 57
2020-02-26T10:06:51-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 58
2020-02-26T10:06:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7ce48>
2020-02-26T10:06:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25908>
2020-02-26T10:06:51-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:51-0300 [BrokerProtocol,32,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:51-0300 [BrokerProtocol,32,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:51-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7ce48>
2020-02-26T10:06:51-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:51-0300 [ClientProtocol,client] connection lost - Number of events: 59
2020-02-26T10:06:51-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fdef0>
2020-02-26T10:06:51-0300 [BrokerProtocol,33,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:56-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 60
2020-02-26T10:06:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25ac8>
2020-02-26T10:06:56-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 61
2020-02-26T10:06:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25d30>
2020-02-26T10:06:56-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:06:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25ac8>
2020-02-26T10:06:56-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:06:56-0300 [BrokerProtocol,34,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:06:56-0300 [BrokerProtocol,34,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:56-0300 [BrokerProtocol,35,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:06:56-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:06:56-0300 [ClientProtocol,client] connection lost - Number of events: 62
2020-02-26T10:06:56-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25908>
2020-02-26T10:06:56-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:56-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:06:56-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:06:56-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:01-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 63
2020-02-26T10:07:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25128>
2020-02-26T10:07:01-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 64
2020-02-26T10:07:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7ca20>
2020-02-26T10:07:01-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25128>
2020-02-26T10:07:01-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:07:01-0300 [BrokerProtocol,36,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:07:01-0300 [BrokerProtocol,36,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:01-0300 [BrokerProtocol,37,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:01-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:07:01-0300 [ClientProtocol,client] connection lost - Number of events: 65
2020-02-26T10:07:01-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b25d30>
2020-02-26T10:07:06-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 66
2020-02-26T10:07:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd898>
2020-02-26T10:07:06-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 67
2020-02-26T10:07:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b910f0>
2020-02-26T10:07:06-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab1fd898>
2020-02-26T10:07:06-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:07:06-0300 [BrokerProtocol,38,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:07:06-0300 [BrokerProtocol,38,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:06-0300 [BrokerProtocol,39,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:06-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:07:06-0300 [ClientProtocol,client] connection lost - Number of events: 68
2020-02-26T10:07:06-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b7ca20>
2020-02-26T10:07:11-0300 [-] 127.0.0.1:51334 - sending MQTT PUBLISH REQUEST - Number of events: 69
2020-02-26T10:07:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20ff60>
2020-02-26T10:07:11-0300 [-] 127.0.0.1:51336 - sending MQTT PUBLISH REQUEST - Number of events: 70
2020-02-26T10:07:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b3e208>
2020-02-26T10:07:11-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efcab20ff60>
2020-02-26T10:07:11-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:07:11-0300 [BrokerProtocol,40,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:07:11-0300 [BrokerProtocol,40,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:11-0300 [BrokerProtocol,41,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:11-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:07:11-0300 [ClientProtocol,client] connection lost - Number of events: 71
2020-02-26T10:07:11-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b910f0>
2020-02-26T10:07:14-0300 [-] Received SIGINT, shutting down.
2020-02-26T10:07:14-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-02-26T10:07:14-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:14-0300 [PublisherApp,client] connection lost - Number of events: 72
2020-02-26T10:07:14-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:14-0300 [PublisherApp,client] connection lost - Number of events: 73
2020-02-26T10:07:14-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-26T10:07:14-0300 [ClientProtocol,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:14-0300 [ClientProtocol,client] connection lost - Number of events: 74
2020-02-26T10:07:14-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efca9b3e208>
2020-02-26T10:07:14-0300 [RouterAppProtocol,3,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:14-0300 [RouterAppProtocol,3,127.0.0.1] connection lost - Number of events: 75
2020-02-26T10:07:14-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:14-0300 [SubscriberApp,client] connection lost - Number of events: 76
2020-02-26T10:07:14-0300 [BrokerProtocol,42,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:14-0300 [-] Main loop terminated.
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:14-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
