2020-02-26T10:07:30-0300 [-] Creating router ...
2020-02-26T10:07:30-0300 [-] Initializing Router - Number of events: 1
2020-02-26T10:07:30-0300 [-] RouterFactory starting on 8081
2020-02-26T10:07:30-0300 [-] Creating fog node ...
2020-02-26T10:07:30-0300 [stdout#info] applications.mqttapp.SubscriberApp
2020-02-26T10:07:30-0300 [-] Initializing Client - Number of events: 2
2020-02-26T10:07:30-0300 [-] Creating fog node ...
2020-02-26T10:07:30-0300 [-] Initializing Server - Number of events: 3
2020-02-26T10:07:30-0300 [-] BrokerFactory starting on 5100
2020-02-26T10:07:30-0300 [-] Creating iot node ...
2020-02-26T10:07:30-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:07:30-0300 [-] Initializing Client - Number of events: 4
2020-02-26T10:07:30-0300 [-] Creating iot node ...
2020-02-26T10:07:30-0300 [stdout#info] applications.mqttapp.PublisherApp
2020-02-26T10:07:30-0300 [-] Initializing Client - Number of events: 5
2020-02-26T10:07:30-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:07:30-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:07:30-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:07:30-0300 [stdout#info] This divice have no simulation core instance
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51430 - Connected to mqtt broker - Number of events: 6
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51430 - sending MQTT SUBSCRIBE REQUEST - Number of events: 7
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51432 - Connected to mqtt broker - Number of events: 8
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51432 - sending MQTT PUBLISH REQUEST - Number of events: 9
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51434 - Connected to mqtt broker - Number of events: 10
2020-02-26T10:07:30-0300 [Uninitialized] 127.0.0.1:51434 - sending MQTT PUBLISH REQUEST - Number of events: 11
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13ac8>
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13cc0>
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13eb8>
2020-02-26T10:07:30-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13ac8>
2020-02-26T10:07:30-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13cc0>
2020-02-26T10:07:30-0300 [BrokerProtocol,0,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:30-0300 [BrokerProtocol,1,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:30-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.KeyError: <applications.routerapp.ClientProtocol object at 0x7f81d0a13c88>
	
2020-02-26T10:07:30-0300 [ClientProtocol,client] connection lost: <applications.routerapp.ClientProtocol object at 0x7f81d0a13c88>
2020-02-26T10:07:30-0300 [ClientProtocol,client] connection lost - Number of events: 12
2020-02-26T10:07:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d0a13eb8>
2020-02-26T10:07:30-0300 [BrokerProtocol,2,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:35-0300 [-] 127.0.0.1:51432 - sending MQTT PUBLISH REQUEST - Number of events: 13
2020-02-26T10:07:35-0300 [-] 127.0.0.1:51434 - sending MQTT PUBLISH REQUEST - Number of events: 14
2020-02-26T10:07:35-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20930b8>
2020-02-26T10:07:35-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20932b0>
2020-02-26T10:07:35-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:35-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20930b8>
2020-02-26T10:07:35-0300 [BrokerProtocol,3,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:40-0300 [-] 127.0.0.1:51432 - sending MQTT PUBLISH REQUEST - Number of events: 15
2020-02-26T10:07:40-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20935f8>
2020-02-26T10:07:40-0300 [-] 127.0.0.1:51434 - sending MQTT PUBLISH REQUEST - Number of events: 16
2020-02-26T10:07:40-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093860>
2020-02-26T10:07:40-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:40-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20935f8>
2020-02-26T10:07:40-0300 [BrokerProtocol,4,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:07:40-0300 [BrokerProtocol,4,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:40-0300 [BrokerProtocol,5,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:40-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:07:40-0300 [ClientProtocol,client] connection lost - Number of events: 17
2020-02-26T10:07:40-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d20932b0>
2020-02-26T10:07:45-0300 [-] 127.0.0.1:51432 - sending MQTT PUBLISH REQUEST - Number of events: 18
2020-02-26T10:07:45-0300 [-] 127.0.0.1:51434 - sending MQTT PUBLISH REQUEST - Number of events: 19
2020-02-26T10:07:45-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093d30>
2020-02-26T10:07:45-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093ef0>
2020-02-26T10:07:45-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:45-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:45-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:45-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
2020-02-26T10:07:45-0300 [Uninitialized] Sorry, we can't find any protocol with these network settings!
2020-02-26T10:07:45-0300 [BrokerProtocol,6,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 187, in dataReceived
	    self.send_package_to_all_subscribers(package)
	  File "/home/rafael/iotfogsim/scinetsim/applications/mqttapp.py", line 192, in send_package_to_all_subscribers
	    self.source_addr = subscriber.transport.getHost().host
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 884, in getHost
	    addr = _getsockname(self.socket)
	builtins.AttributeError: 'Server' object has no attribute 'socket'
	
2020-02-26T10:07:45-0300 [BrokerProtocol,6,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:45-0300 [ClientProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 132, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 134, in dataReceived
	    self.simulation_core.allProtocols.remove(self)
	builtins.AttributeError: 'NoneType' object has no attribute 'allProtocols'
	
2020-02-26T10:07:45-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093d30>
2020-02-26T10:07:45-0300 [ClientProtocol,client] connection lost: Connection was closed cleanly.
2020-02-26T10:07:45-0300 [ClientProtocol,client] connection lost - Number of events: 20
2020-02-26T10:07:45-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093860>
2020-02-26T10:07:45-0300 [BrokerProtocol,7,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:46-0300 [-] Received SIGINT, shutting down.
2020-02-26T10:07:46-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:46-0300 [PublisherApp,client] connection lost - Number of events: 21
2020-02-26T10:07:46-0300 [SubscriberApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:46-0300 [SubscriberApp,client] connection lost - Number of events: 22
2020-02-26T10:07:46-0300 [RouterAppProtocol,3,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:46-0300 [RouterAppProtocol,3,127.0.0.1] connection lost - Number of events: 23
2020-02-26T10:07:46-0300 [applications.mqttapp.BrokerFactory] (TCP Port 5100 Closed)
2020-02-26T10:07:46-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-02-26T10:07:46-0300 [BrokerProtocol,8,127.0.0.1] The requested subscriber is no longer available in subscribers list
2020-02-26T10:07:46-0300 [ClientProtocol,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:46-0300 [ClientProtocol,client] connection lost - Number of events: 24
2020-02-26T10:07:46-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f81d2093ef0>
2020-02-26T10:07:46-0300 [PublisherApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-26T10:07:46-0300 [PublisherApp,client] connection lost - Number of events: 25
2020-02-26T10:07:46-0300 [-] Main loop terminated.
2020-02-26T10:07:46-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2020-02-26T10:07:46-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/endpoints.py", line 125, in connectionMade
	    self._connectedDeferred.callback(self._wrappedProtocol)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
	    self._startRunCallbacks(result)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/routerapp.py", line 73, in save_protocol
	    proto.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 86, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 217, in __init__
	    self.create_connection(self.simulation_core, self.device1, self.device2)
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 223, in create_connection
	    x1 = self.device1.visual_component.x
	builtins.AttributeError: 'ClientProtocol' object has no attribute 'visual_component'
	
