2020-04-10T11:39:35-0300 [-] Creating router ...
2020-04-10T11:39:35-0300 [-] Initializing Router - Number of events: 1
2020-04-10T11:39:35-0300 [-] RouterFactory starting on 8081
2020-04-10T11:39:35-0300 [-] Creating AccessPoint station ...
2020-04-10T11:39:35-0300 [stderr#error] Exception in Tkinter callback
2020-04-10T11:39:35-0300 [stderr#error] Traceback (most recent call last):
2020-04-10T11:39:35-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-04-10T11:39:35-0300 [stderr#error]     return self.func(*args)
2020-04-10T11:39:35-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 106, in <lambda>
2020-04-10T11:39:35-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-04-10T11:39:35-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 60, in open_project
2020-04-10T11:39:35-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-04-10T11:39:35-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 149, in load_nodes
2020-04-10T11:39:35-0300 [stderr#error]     ap = AccessPoint(simulation_core, access_point['simulation_ip'], access_point['port'], access_point['real_ip'], access_point['simulation_ip'], access_point['id'], access_point['TBTT'], access_point['SSID'], access_point['WPA2_password'], access_point['icon'], access_point['is_wireless'], access_point['x'], access_point['y'], access_point['application'])
2020-04-10T11:39:35-0300 [stderr#error] KeyError: 'application'
2020-04-10T11:39:35-0300 [stdout#info] This divice have no simulation core instance
2020-04-10T11:40:34-0300 [-] Received SIGINT, shutting down.
2020-04-10T11:40:34-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-04-10T11:40:34-0300 [-] Main loop terminated.
