2020-06-07T18:11:04-0300 [-] Creating router ...
2020-06-07T18:11:04-0300 [-] Initializing Router - Number of events: 1
2020-06-07T18:11:04-0300 [-] RouterFactory starting on 8081
2020-06-07T18:11:04-0300 [-] Creating AccessPoint station ...
2020-06-07T18:11:04-0300 [-] Initializing Access Point - Number of events: 2
2020-06-07T18:11:05-0300 [-] Initializing Server - Number of events: 3
2020-06-07T18:11:05-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T18:11:05-0300 [-] Initializing sensor node - Number of events: 4
2020-06-07T18:11:06-0300 [stdout#info] Not connected to a wireless access point
2020-06-07T18:11:06-0300 [stdout#info] Assossiated to : notebook 1
2020-06-07T18:11:06-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T18:11:06-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T18:11:07-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f2a7b585a90>
2020-06-07T18:11:07-0300 [applications.httpapp.HttpServerAppFactory] Connection received - Number of events: 5
2020-06-07T18:11:07-0300 [HttpServerAppProtocol,0,127.0.0.1] Received from client HTTP 1.0 / GET request
2020-06-07T18:11:07-0300 [HttpServerAppProtocol,0,127.0.0.1] Sending HTTP RESPONSE - Number of events: 6
2020-06-07T18:11:08-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 23, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 197, in forward_packages
	    for pakage in self.ap_factory.running_protocol._out_buffer.copy:
	builtins.TypeError: 'builtin_function_or_method' object is not iterable
	
2020-06-07T18:11:24-0300 [-] Received SIGINT, shutting down.
2020-06-07T18:11:24-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T18:11:24-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T18:11:24-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-06-07T18:11:24-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost - Number of events: 7
2020-06-07T18:11:24-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f2a7b585a90>
2020-06-07T18:11:24-0300 [-] Main loop terminated.
