2020-06-07T18:11:31-0300 [-] Creating router ...
2020-06-07T18:11:31-0300 [-] Initializing Router - Number of events: 1
2020-06-07T18:11:32-0300 [-] RouterFactory starting on 8081
2020-06-07T18:11:32-0300 [-] Creating AccessPoint station ...
2020-06-07T18:11:32-0300 [-] Initializing Access Point - Number of events: 2
2020-06-07T18:11:33-0300 [-] Initializing Server - Number of events: 3
2020-06-07T18:11:33-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T18:11:33-0300 [-] Initializing sensor node - Number of events: 4
2020-06-07T18:11:34-0300 [stdout#info] Not connected to a wireless access point
2020-06-07T18:11:34-0300 [stdout#info] Assossiated to : notebook 1
2020-06-07T18:11:34-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T18:11:34-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T18:11:35-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f2e382d4278>
2020-06-07T18:11:35-0300 [applications.httpapp.HttpServerAppFactory] Connection received - Number of events: 5
2020-06-07T18:11:35-0300 [HttpServerAppProtocol,0,127.0.0.1] Received from client HTTP 1.0 / GET request
2020-06-07T18:11:35-0300 [HttpServerAppProtocol,0,127.0.0.1] Sending HTTP RESPONSE - Number of events: 6
2020-06-07T18:11:36-0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "run_iotfogsim.py", line 23, in <module>
	    reactor.run()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
	    self.mainLoop()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 198, in forward_packages
	    destiny_addr, destiny_port, source_addr, source_port, _type, payload = self.extract_package_contents(package)
	builtins.AttributeError: 'AccessPointApp' object has no attribute 'extract_package_contents'
	
2020-06-07T18:12:34-0300 [-] Received SIGINT, shutting down.
2020-06-07T18:12:34-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-06-07T18:12:34-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost - Number of events: 7
2020-06-07T18:12:34-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T18:12:34-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f2e382d4278>
2020-06-07T18:12:34-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T18:12:34-0300 [-] Main loop terminated.
