2020-06-07T12:26:23-0300 [-] Initializing Server - Number of events: 1
2020-06-07T12:26:24-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T12:26:24-0300 [-] Creating router ...
2020-06-07T12:26:24-0300 [-] Initializing Router - Number of events: 2
2020-06-07T12:26:24-0300 [-] RouterFactory starting on 8081
2020-06-07T12:26:24-0300 [-] Creating AccessPoint station ...
2020-06-07T12:26:25-0300 [-] Initializing Access Point - Number of events: 3
2020-06-07T12:26:25-0300 [-] Initializing sensor node - Number of events: 4
2020-06-07T12:26:26-0300 [stdout#info] Not connected to a wireless access point
2020-06-07T12:26:26-0300 [stdout#info] Assossiated to : notebook 1
2020-06-07T12:26:26-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:26:26-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:26:26-0300 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
	    why = selectable.doWrite()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
	    self._connectDone()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
	    self.connectionMade()
	  File "/home/rafael/iotfogsim/scinetsim/applications/accesspointapp.py", line 25, in connectionMade
	    self.create_connection_animation()
	  File "/home/rafael/iotfogsim/scinetsim/applications/applicationcomponent.py", line 107, in create_connection_animation
	    con = Connection(self.simulation_core, self, self.transport.getPeer().host, self.transport.getPeer().port)
	builtins.AttributeError: 'AccessPointAppProtocol' object has no attribute 'simulation_core'
	
2020-06-07T12:26:26-0300 [stdout#info] {b'{"destiny_addr": "127.0.0.1", "destiny_port": 8080, "source_addr": "127.0.0.1", "source_port": 8888, "type": "http", "payload": "HTTP 1.0 / GET request"}'}
2020-06-07T12:30:11-0300 [-] Received SIGINT, shutting down.
2020-06-07T12:30:11-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T12:30:11-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T12:30:11-0300 [-] Main loop terminated.
