2020-06-07T12:07:58-0300 [-] Initializing Server - Number of events: 1
2020-06-07T12:07:58-0300 [-] HttpServerAppFactory starting on 8080
2020-06-07T12:07:58-0300 [-] Creating router ...
2020-06-07T12:07:58-0300 [-] Initializing Router - Number of events: 2
2020-06-07T12:07:59-0300 [-] RouterFactory starting on 8081
2020-06-07T12:07:59-0300 [-] Creating AccessPoint station ...
2020-06-07T12:07:59-0300 [-] Initializing Access Point - Number of events: 3
2020-06-07T12:07:59-0300 [-] Initializing sensor node - Number of events: 4
2020-06-07T12:08:00-0300 [stdout#info] Not connected to a wireless access point
2020-06-07T12:08:00-0300 [stdout#info] Assossiated to : notebook 1
2020-06-07T12:08:00-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:08:00-0300 [stdout#info] This divice have no simulation core instance
2020-06-07T12:08:00-0300 [stdout#info] {b'{"destiny_addr": "127.0.0.1", "destiny_port": 8080, "source_addr": "127.0.0.1", "source_port": 8888, "type": "http", "payload": "HTTP 1.0 / GET request"}'}
2020-06-07T12:08:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9f454b02e8>
2020-06-07T12:08:00-0300 [applications.httpapp.HttpServerAppFactory] Connection received - Number of events: 5
2020-06-07T12:08:00-0300 [HttpServerAppProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
	    return self._dataReceived(data)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rafael/iotfogsim/scinetsim/applications/httpapp.py", line 126, in dataReceived
	    destiny_addr, destiny_port, source_addr, source_port, _type, payload = extract_package_contents(data)
	builtins.NameError: name 'extract_package_contents' is not defined
	
2020-06-07T12:08:00-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost: name 'extract_package_contents' is not defined
2020-06-07T12:08:00-0300 [HttpServerAppProtocol,0,127.0.0.1] connection lost - Number of events: 6
2020-06-07T12:08:00-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7f9f454b02e8>
2020-06-07T12:08:35-0300 [-] Received SIGINT, shutting down.
2020-06-07T12:08:35-0300 [applications.httpapp.HttpServerAppFactory] (TCP Port 8080 Closed)
2020-06-07T12:08:35-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-07T12:08:35-0300 [-] Main loop terminated.
