2021-02-13T02:11:23-0300 [-] Creating router ...
2021-02-13T02:11:23-0300 [-] Initializing Router - Number of events: 1
2021-02-13T02:11:23-0300 [-] Initializing Server - Number of events: 2
2021-02-13T02:11:23-0300 [-] Initializing Client - Number of events: 3
2021-02-13T02:11:23-0300 [-] Initializing sink node - Number of events: 4
2021-02-13T02:11:23-0300 [-] Initializing sensor node - Number of events: 5
2021-02-13T02:11:24-0300 [-] Initializing sensor node - Number of events: 6
2021-02-13T02:11:24-0300 [-] Initializing repeater node - Number of events: 7
2021-02-13T02:11:25-0300 [-] Initializing repeater node - Number of events: 8
2021-02-13T02:11:30-0300 [-] RouterFactory starting on 8081
2021-02-13T02:11:30-0300 [-] BrokerFactory starting on 5100
2021-02-13T02:11:30-0300 [stdout#info] ========= sensor_1 ==========
2021-02-13T02:11:30-0300 [stdout#info] sensor_1  <------->  sensor_2
2021-02-13T02:11:30-0300 [stdout#info] sensor_1  <------->  wsn_sink
2021-02-13T02:11:30-0300 [stdout#info] =============================
2021-02-13T02:11:30-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2021-02-13T02:11:30-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 252, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 153, in start
	    LoopingCall(self.collect_and_send_data).start(self.interval)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/task.py", line 194, in start
	    self()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 163, in collect_and_send_data
	    data = "{'voltage': {}, 'frequency':{}}".format(voltage, frequency)
	builtins.KeyError: "'voltage'"
	
2021-02-13T02:11:30-0300 [stdout#info] ========= sensor_2 ==========
2021-02-13T02:11:30-0300 [stdout#info] sensor_2  <------->  sensor_1
2021-02-13T02:11:30-0300 [stdout#info] sensor_2  <------->  wsn_repeater_1
2021-02-13T02:11:30-0300 [stdout#info] sensor_2  <------->  wsn_sink
2021-02-13T02:11:30-0300 [stdout#info] =============================
2021-02-13T02:11:30-0300 [twisted.internet.defer#critical] Unhandled error in Deferred:
2021-02-13T02:11:30-0300 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/rafael/iotfogsim/scinetsim/scinetsim/standarddevice.py", line 252, in run
	    self.application.start(nearby_devices_list)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 153, in start
	    LoopingCall(self.collect_and_send_data).start(self.interval)
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/task.py", line 194, in start
	    self()
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/home/rafael/iotfogsim/vm/lib/python3.6/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/rafael/iotfogsim/scinetsim/applications/wsnapp.py", line 163, in collect_and_send_data
	    data = "{'voltage': {}, 'frequency':{}}".format(voltage, frequency)
	builtins.KeyError: "'voltage'"
	
2021-02-13T02:11:30-0300 [stdout#info] ========= wsn_repeater_1 ==========
2021-02-13T02:11:30-0300 [stdout#info] wsn_repeater_1  <------->  sensor_2
2021-02-13T02:11:30-0300 [stdout#info] =============================
2021-02-13T02:11:30-0300 [stdout#info] This divice have no simulation core instance
2021-02-13T02:11:30-0300 [stdout#info] This divice have no simulation core instance
2021-02-13T02:11:30-0300 [stdout#info] This divice have no simulation core instance
2021-02-13T02:11:30-0300 [Uninitialized] 
	
	      SCADA
	127.0.0.1:55892 - Connected to mqtt broker - Number of events: 9
2021-02-13T02:11:30-0300 [Uninitialized] 
	
	      SCADA
	127.0.0.1:55892 - sending MQTT SUBSCRIBE REQUEST - Number of events: 10
2021-02-13T02:11:30-0300 [twisted.internet.endpoints.OneShotFactory#info] Starting factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efc067f1d68>
2021-02-13T02:11:31-0300 [stdout#info] ========= wsn_repeater_2 ==========
2021-02-13T02:11:31-0300 [stdout#info] =============================
2021-02-13T02:12:02-0300 [-] SCADA - Saving to the database. - Number of events: 11
2021-02-13T02:13:19-0300 [-] Received SIGINT, shutting down.
2021-02-13T02:13:19-0300 [twisted.internet.endpoints.OneShotFactory#info] Stopping factory <twisted.internet.endpoints.connectProtocol.<locals>.OneShotFactory object at 0x7efc067f1d68>
2021-02-13T02:13:19-0300 [SCADAApp,client] connection lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2021-02-13T02:13:19-0300 [SCADAApp,client] connection lost - Number of events: 12
2021-02-13T02:13:19-0300 [applications.pesquisaapp.BrokerFactory] (TCP Port 5100 Closed)
2021-02-13T02:13:19-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2021-02-13T02:13:19-0300 [-] Main loop terminated.
