2020-06-03T23:44:49-0300 [-] Creating router ...
2020-06-03T23:44:49-0300 [-] Initializing Router - Number of events: 1
2020-06-03T23:44:49-0300 [-] RouterFactory starting on 8081
2020-06-03T23:44:49-0300 [-] Creating AccessPoint station ...
2020-06-03T23:44:49-0300 [-] Initializing Access Point - Number of events: 2
2020-06-03T23:44:50-0300 [stderr#error] Exception in Tkinter callback
2020-06-03T23:44:50-0300 [stderr#error] Traceback (most recent call last):
2020-06-03T23:44:50-0300 [stderr#error]   File "/usr/lib/python3.6/tkinter/__init__.py", line 1708, in __call__
2020-06-03T23:44:50-0300 [stderr#error]     return self.func(*args)
2020-06-03T23:44:50-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 107, in <lambda>
2020-06-03T23:44:50-0300 [stderr#error]     btn_open = ttk.Button(window, text="Open Project",command=lambda:open_project(window,simulation_core))
2020-06-03T23:44:50-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 61, in open_project
2020-06-03T23:44:50-0300 [stderr#error]     load_nodes(selected_project_name, simulation_core)
2020-06-03T23:44:50-0300 [stderr#error]   File "/home/rafael/iotfogsim/scinetsim/scinetsim/configurations.py", line 158, in load_nodes
2020-06-03T23:44:50-0300 [stderr#error]     sr = StandardServerDevice(simulation_core, server['port'], server['real_ip'], server['simulation_ip'], server['id'], server['name'], server['icon'], server['is_wireless'], server['x'], server['y'], server['application'], server['coverage_area_radius'])
2020-06-03T23:44:50-0300 [stderr#error] KeyError: 'port'
2020-06-03T23:44:50-0300 [stdout#info] This divice have no simulation core instance
2020-06-03T23:49:03-0300 [-] Received SIGINT, shutting down.
2020-06-03T23:49:03-0300 [applications.routerapp.RouterFactory] (TCP Port 8081 Closed)
2020-06-03T23:49:03-0300 [-] Main loop terminated.
